import os
import secrets
from dotenv import load_dotenv

load_dotenv()
APP_SECRET_KEY = secrets.token_hex(16)
SQLALCHEMY_HOST = os.getenv('SQLALCHEMY_HOST')
SQLALCHEMY_PORT= os.getenv('SQLALCHEMY_PORT')
SQLALCHEMY_DB_USER= os.getenv('SQLALCHEMY_DB_USER')
SQLALCHEMY_DB_PASSWORD= os.getenv('SQLALCHEMY_DB_PASSWORD')
SQLALCHEMY_DB_NAME= os.getenv('SQLALCHEMY_DB_NAME')
JWT_SECRET_KEY= os.getenv('JWT_SECRET_KEY')
URI_BASE = f'{SQLALCHEMY_DB_USER}:{SQLALCHEMY_DB_PASSWORD}@{SQLALCHEMY_HOST}:{SQLALCHEMY_PORT}/{SQLALCHEMY_DB_NAME}'
revoked_tokens = set()
