version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: dockerhub-flask_live_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://user_admin:12345@localhost:5432/testdb
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=user_admin
      - POSTGRES_DB=testdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}