"""empty message

Revision ID: 94253f02d670
Revises: 82fa8125b0e0
Create Date: 2023-10-14 23:23:45.091735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94253f02d670'
down_revision = '82fa8125b0e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'status')
    # ### end Alembic commands ###
